# Generated by Django 5.0.6 on 2024-07-17 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacionreserva',
            name='cantidad_servicios',
        ),
        migrations.RemoveField(
            model_name='habitacionreserva',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='habitacionreserva',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='habitacionreserva',
            name='habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.habitacion'),
        ),
        migrations.AlterField(
            model_name='habitacionreserva',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.servicio'),
        ),
    ]
