# Generated by Django 5.0.6 on 2024-07-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='cantidad_banos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='cantidad_personas',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
