# Generated by Django 5.0.6 on 2024-07-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
