# Generated by Django 5.0.6 on 2024-07-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_habitacion_cantidad_banos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='fecha_final',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fecha_inicio',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
